### ISSUE TITLE
Crashes When Quickly Tapping Between Dashboard and Other Tab Bar Items

### ISSUE THREAD

**Issue by jyee999** [Dimillian/ACHNBrowserUI#296]
App crashes when you repeatedly tap different bottom row items quickly.  I suspect that it might actually be something with the DASHBOARD button because tapping all the other buttons didn't seem to cause a crash.

App Version 1.8.3 (070812020)
Game Patch Data 1.3.0
iPhone X on iOS 13.4.1

**Comment by TheVaan** [comment]
Hi!

I can’t reproduce this under iOS 13.5.1. 
iOS 13.4 had several bugs in SwiftUI that has been fixed by Apple in 13.5. This must be one of them.
If possible, please update to iOS 13.5.1.

**Comment by jyee999** [comment]
I've updated the iPhone X to latest iOS and still encountered the crash.  I've also tested on iPad Pro 12.9 (2nd generation), iPhone XS Max and an iPhone 6S.  All devices are on 13.5.1.

Strangely I haven't been able to crash it on the iPhone 6S but it crashes very quickly on the iPhone XS Max but not as quickly on the iPad Pro and iPhone X.  (Timing related?)

Attached is screen recording of the crash on iPad Pro switching between the Dashboard and the catalog.  You can see that continually tapping the button bar items redraw and create new menu items even though the screen hasn't changed.  Not sure if this is a clue.

Maybe someone else could try to reproduce.

[achelper-crash-296.mp4.zip](https://github.com/Dimillian/ACHNBrowserUI/files/4906725/achelper-crash-296.mp4.zip)

**Comment by TheVaan** [comment]
I'm sorry that my solution didn't worked. I've reopened the issue and assigned @Dimillian to take a look on that. Maybe it has been fixed for upcoming iOS 14 release, because he rewrote parts of the app for iOS 14 and the newest SwiftUI version.

**Comment by jyee999** [comment]
Could not reproduce with iOS 14 when it went live.  Thanks!
